[package]
name = "distrail-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "distrailrs"
path = "src/lib/mod.rs"

[dependencies]
byteorder = "1.5.0"
memmap2 = { version = "0.9.4" }
tokio = { version = "1.38.0", features = ["full"] }
